### ISSUE TITLE
画像のトリミング機能

### ISSUE THREAD

**Issue by watanabe-sota** [Stickers-hackathon/stickers#19]
画像のトリミング機能追加

ステッカーの背景対策として、固定大きさの丸もしくは四角のステッカーの領域でトリミングして、想定より大きくならないようにする

**Comment by watanabe-sota** [comment]
pages/testTrimming  でテスト実装予定

**Comment by hourglasshoro** [comment]
参考
https://codesandbox.io/s/q8q1mnr01w?file=/src/styles.js
